### ISSUE TITLE
About some runtime errors

### ISSUE THREAD

**Issue by abds100** [360modder/signauth#1]
Hi I meet a problem when I'm running signauth.py to pre-trained your model, it turns out some errors
"usage: signauth.py [-h] [--scan] image  
  signauth.py: error: the following arguments are required: image"
and accordingly when I finish trainning the model and run predict.py, it turns out
"RuntimeError: output with shape [1, 256, 256] doesn't match the broadcast shape [3, 256, 256]"
Can you please help me to resolve this issue?

**Comment by clitic** [comment]
I strongly recommend to take a look of this project on [google colab](https://colab.research.google.com/github/360modder/signauth/blob/master/others/SignAuth_Google_Colab.ipynb)  it may solve your issues.

**answers per your issue**

the runtime complexities are due to the images we are feeding, as they are raw images so before training model you have to preprocess them.

```shell
python preprocessing/preprocessor.py --process=train,test,predict --backup --overwrite
```

this resize and crop images in train test and predict folder then you can run

```shell
python train.py
python predict.py
```

moreover signauth.py use a jitted pre-trained so the error `"usage: signauth.py [-h] [--scan] image
signauth.py: error: the following arguments are required: image"` is likely due to for not supplying a image file to script.

**Comment by abds100** [comment]
Many thanks for reply!
I have never used google colab before, so maybe I need to spend a bit of time to learn about it. I don't know what should I type in "image_path".

About the issue
I did as your reply said and when I ran predict.py again I met another error.
`TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`
I have managed to fix it. 
`index = output.data.cpu().numpy().argmax()`

Other issues
(1) Can you please tell approximately how many images should I put in trainning dataset? I want to try signatures written in languages other than English.
(2) Can you please tell which specific CNN model does your Signauth Model based on or you just create a new one? I have already tried LeNet5, VGG and AlexNet.

**Comment by clitic** [comment]
in "image_path" you have to provide the image path. e.g. "singnature_img.jpg"

`signauth.py signature_img.jpg --scan`

- Issue 1

you can use any no. of images in training and testing dataset. if you train with more images then train time will be more. you can also use batchsize and no. of epochs as per your memory. you can directly change hyper parameters from command line use.

```shell
python train.py --batchsize=20 --epochs=10
```

cnn for image classification is independent of any language it uses different weights and baisis. conclusion, you can use any other language than english.

**note:** the training will we more precise if images will have clean white background and signature in black color.

- Issue 2

Signauth is based convolution neural network (CNN) which is it self independent of any other popular network. conclusion, I created a new one.

**Comment by abds100** [comment]
Thanks very much for your prompt reply! Now I fully understand how things work in google colab.
When I am trying to build a GUI file to make those prediction results have a better visual effect, the displayed result turns out to be fake all the time, although the image I choose is a real signature. Can you please have a look on my code?

`
from PyQt5.QtWidgets import (QWidget,QLCDNumber,QSlider,QMainWindow,
                             QGridLayout,QApplication,QPushButton, QLabel, QLineEdit)

from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
import sys
from PyQt5.QtCore import Qt
from PIL import Image
from models import *
from predict import device, classes, img_path, model

class Ui_example(QWidget):
    def __init__(self):
        super().__init__()
        self.layout = QGridLayout(self)
        self.label_image = QLabel(self)
        self.label_predict_result = QLabel('Result',self)
        self.label_predict_result_display = QLabel(self)


        self.button_search_image = QPushButton('Choose image',self)
        self.button_run = QPushButton('Start to recognize',self)
        self.setLayout(self.layout)
        self.initUi()

    def initUi(self):

        self.layout.addWidget(self.label_image,1,1,3,2)
        self.layout.addWidget(self.button_search_image,1,3,1,2)
        self.layout.addWidget(self.button_run,3,3,1,2)
        self.layout.addWidget(self.label_predict_result,4,3,1,1)
        self.layout.addWidget(self.label_predict_result_display,4,4,1,1)

        self.button_search_image.clicked.connect(self.openimage)
        self.button_run.clicked.connect(self.run)

        self.setGeometry(300,300,300,300)
        self.setWindowTitle('Signauth')
        self.show()

    def openimage(self):
        global fname
        imgName, imgType = QFileDialog.getOpenFileName(self, "Choose image", "", "*.jpg;;*.png;;All Files(*)")
        jpg = QPixmap(imgName).scaled(self.label_image.width(), self.label_image.height())
        self.label_image.setPixmap(jpg)
        fname = imgName



    def run(self):
        global fname
        file_name = str(fname)
        img = Image.open(file_name)

        a = model.predict(model, device, img_path, classes=classes, transform=transform)
        self.label_predict_result_display.setText(a)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = Ui_example()
    sys.exit(app.exec_())
`

**Comment by clitic** [comment]
![Video_21-05-09_22-55-18](https://user-images.githubusercontent.com/71246790/117582841-a24e2700-b121-11eb-9348-0655083c6e8a.gif)

As per your issue signauth is binded with gui correctly in two scipts. use production_gui.py if you need less code

- Developer Model (gui.py)

```python
# Gui Imports
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QWidget, QLCDNumber, QSlider, QMainWindow, QGridLayout, QApplication, QPushButton, QLabel, QLineEdit, QCheckBox

# SignAuth Imports
import torch
from PIL import Image # for image processing
import cv2 # for image processing
import numpy as np # for image processing
import os, pathlib, threading # These can be removed by few modifications
from models import *


class SignAuthWindow(QWidget):
    def __init__(self):
        super(SignAuthWindow, self).__init__()

        self.setWindowTitle("SignAuth")
        self.setGeometry(300, 300, 300, 300)
        self.layout = QGridLayout(self)
        self.setLayout(self.layout)        
        self.label_image = QLabel("", self)
        self.layout.addWidget(self.label_image, 1, 1, 3, 2)
        self.loaded_image_path = QLabel("Loading SignAuth Model", self)
        self.layout.addWidget(self.loaded_image_path, 4, 2, 2, 2)
        self.imageprocessing = QCheckBox("Pre-Process Image", self)
        self.imageprocessing.setChecked(True)
        self.layout.addWidget(self.imageprocessing, 4, 1, 1, 1)
        self.label_predict_result = QLabel("Result:", self)
        self.layout.addWidget(self.label_predict_result, 4, 3, 1, 1)
        self.label_predict_result_display = QLabel("", self)
        self.layout.addWidget(self.label_predict_result_display, 4, 4, 1, 1)
        self.button_search_image = QPushButton("Choose Image", self)
        self.layout.addWidget(self.button_search_image, 1, 3, 1, 2)
        self.button_run = QPushButton("Start To Recognize", self)
        self.layout.addWidget(self.button_run, 3, 3, 1, 2)

        self.button_search_image.clicked.connect(self.openimage)
        self.button_run.clicked.connect(self.run)

        threading.Thread(target=self.SetupSignAuth).start()

    def SetupSignAuth(self):
        self.fname = ""
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.checkpoint = torch.load("models/model.pth")
        self.model = ConvNet(num_classes=num_classes).to(self.device)
        self.model.load_state_dict(self.checkpoint)
        self.model.eval()
        # self.classes = sorted([folder.name.split("/")[-1] for folder in pathlib.Path("data/train").iterdir()]) # Use when using more classes
        self.classes = ["Fake", "Real"]
        self.loaded_image_path.setText("Model Loaded Choose A Image")

    def openimage(self):
        imgName, imgType = QFileDialog.getOpenFileName(self, "Choose image", "", "*.jpg;;*.png;;All Files(*)")
        jpg = QPixmap(imgName).scaled(self.label_image.width(), self.label_image.height())
        self.label_image.setPixmap(jpg)
        self.fname = imgName
        self.loaded_image_path.setText("Image Name: " + os.path.basename(imgName))

    def run(self):
        if self.imageprocessing.isChecked:
            self.processimage(self.fname, scan=True)
            self.fname = "temp.jpg"

        prediction = self.model.predict(self.model, self.device, self.fname, classes=self.classes, transform=transform)
        self.label_predict_result_display.setText(prediction)

    def processimage(self, img_path, scan=False):

        def scaneffects(img):
            dilated_img = cv2.dilate(img, np.ones((7, 7), np.uint8))
            bg_img = cv2.medianBlur(dilated_img, 15)
            diff_img = 255 - cv2.absdiff(img, bg_img)
            norm_img = diff_img.copy() 
            cv2.normalize(diff_img, norm_img, alpha=0, beta=255, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_8UC1)
            _, thr_img = cv2.threshold(norm_img, 230, 0, cv2.THRESH_TRUNC)
            cv2.normalize(thr_img, thr_img, alpha=0, beta=255, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_8UC1)
            return thr_img


        img = Image.open(img_path)
        img.convert("LA")
        width, height = img.size
        cutfactor = max(img.size)
        left, top, right, bottom = int((width-cutfactor)/2), int((height-cutfactor)/2), int((width+cutfactor)/2), int((height+cutfactor)/2)
        bg = Image.new("RGB", (right-left, bottom-top), (255, 255, 255))
        bg.paste(img, (-left, -top))
        img = bg
        img.thumbnail((256, 256), Image.ANTIALIAS)
        img.save("./temp.jpg")

        if scan:
            img = cv2.imread("./temp.jpg")
            cv2.imwrite("./temp.jpg", scaneffects(img))


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)

    window = SignAuthWindow()
    window.show()

    sys.exit(app.exec_())

```

- Production Model (production_gui.py)

to use this run commands 

```shell
python train.py
python models/production.py
```

```python
# Gui Imports
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QWidget, QLCDNumber, QSlider, QMainWindow, QGridLayout, QApplication, QPushButton, QLabel, QLineEdit

# SignAuth Imports
import subprocess
import os # These can be removed by few modifications


class SignAuthWindow(QWidget):
    def __init__(self):
        super(SignAuthWindow, self).__init__()

        self.setWindowTitle("SignAuth")
        self.setGeometry(300, 300, 300, 300)
        self.layout = QGridLayout(self)
        self.setLayout(self.layout)        
        self.label_image = QLabel("", self)
        self.layout.addWidget(self.label_image, 1, 1, 3, 2)
        self.loaded_image_path = QLabel("SignAuth Model Will Be Loaded During Runtime", self)
        self.layout.addWidget(self.loaded_image_path, 4, 2, 2, 2)
        self.label_predict_result = QLabel("Result:", self)
        self.layout.addWidget(self.label_predict_result, 4, 3, 1, 1)
        self.label_predict_result_display = QLabel("", self)
        self.layout.addWidget(self.label_predict_result_display, 4, 4, 1, 1)
        self.button_search_image = QPushButton("Choose Image", self)
        self.layout.addWidget(self.button_search_image, 1, 3, 1, 2)
        self.button_run = QPushButton("Start To Recognize", self)
        self.layout.addWidget(self.button_run, 3, 3, 1, 2)

        self.button_search_image.clicked.connect(self.openimage)
        self.button_run.clicked.connect(self.run)

        self.fname = ""

    def openimage(self):
        imgName, imgType = QFileDialog.getOpenFileName(self, "Choose image", "", "*.jpg;;*.png;;All Files(*)")
        jpg = QPixmap(imgName).scaled(self.label_image.width(), self.label_image.height())
        self.label_image.setPixmap(jpg)
        self.fname = imgName
        self.loaded_image_path.setText("Image Name: " + os.path.basename(imgName))

    def run(self):
        prediction = subprocess.check_output(["python", "production/signauth.py", self.fname ,"--scan"])
        self.label_predict_result_display.setText(prediction.decode("utf-8"))


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)

    window = SignAuthWindow()
    window.show()

    sys.exit(app.exec_())

```

**Comment by abds100** [comment]
Greatly appreciated for your patience and guidance! I really gain a lot from your model and instructions. 
This is my first time ever to open an issue on github. I think I'm very lucky to get your help here. Thank you once again for modifying code for me!
Next I plan to make some changes of model's code to have a better accuracy using sigatures written in language except English. Could you give me any suggestions on this idea?

**Comment by clitic** [comment]
use clear images for training and testing and you can change some values in **models/__init__.py**
